### ISSUE TITLE
[BUG] specifying vertex_subset throws invalid syntax error

### ISSUE THREAD

**Issue by drabastomek** [rapidsai/cugraph#1229]
**Describe the bug**
When calling `.degree()` or `in_degree()` or any method that supports `vertex_subset` parameter throws a syntax error from `ast`. I think the issue is on line 1086 (and other) in `structure/graph.py`.

Full stack:

```
Traceback (most recent call last):

  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-20-07d3dff11144>", line 1, in <module>
    g.in_degree([0,1])

  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cugraph/structure/graph.py", line 931, in in_degree
    return self._degree(vertex_subset, x=1)

  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cugraph/structure/graph.py", line 1086, in _degree
    df = df.query("`vertex` in @vertex_subset")

  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/dataframe.py", line 4202, in query
    boolmask = queryutils.query_execute(self, expr, callenv)

  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/utils/queryutils.py", line 200, in query_execute
    compiled = query_compile(expr)

  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/utils/queryutils.py", line 133, in query_compile
    info = query_parser(expr)

  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/utils/queryutils.py", line 56, in query_parser
    tree = ast.parse(text)

  File "/opt/conda/envs/rapids/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)

  File "<unknown>", line 1
    `vertex` in __CUDF_ENVREF__vertex_subset
    ^
SyntaxError: invalid syntax
```

**Steps/Code to reproduce bug**
```
gg = cugraph.Graph()

edgelist_df = cudf.DataFrame([
    (0,1,2)
    , (1,2,1)
    , (0,2,3)
    , (2,3,1)
], columns=['src', 'dst', 'weight'])

gg.from_cudf_edgelist(
    edgelist_df
    , source='src'
    , destination='dst'
    , edge_attr='weight'
    , renumber=False
)

gg.degree([0,1])
```

**Expected behavior**
A `cudf` with a subset of vertices and their degrees is returned.

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuGraph install: Docker
   - latest from rapids-nightly

**Comment by Iroy30** [comment]
Addressed in #1237
