### ISSUE TITLE
[BUG] view_adj_list() results in crash on weighted grapha during jaccard and sssp algorithms

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#167]
**Describe the bug**
View_adj_list() and view_tanspose_adj_list() result in crash (sssp and jaccard) only when the graph has weights.
The crash happens in an RMM_FREE but in different ways as SSSP hangs and jaccard doesn't.

**To Reproduce**
I used cugraph_time.py : https://drive.google.com/file/d/1nIoL6ORhbvf2qzvEdvj-nW-OCCdPmpUJ/view?usp=sharing

```
python cugraph_time.py /datasets/networks/netscience.mtx --algo jaccard --auto_csr 0
python cugraph_time.py /datasets/networks/netscience.mtx --algo sssp --auto_csr 0
```

**Expected behavior**
We expect this to pass

**Screenshots**
```
(cugraph_dev) afender@strata3:~/sw$ python cugraph_time.py /datasets/networks/netscience.mtx --algo sssp --auto_csr 0
280.143,0.001,Traceback (most recent call last):
  File "cugraph_time.py", line 110, in <module>
    sssp_time = sssp_call(G, args.source)
  File "cugraph_time.py", line 48, in sssp_call
    df = cugraph.sssp(G,start)
  File "cugraph/sssp/sssp_wrapper.pyx", line 25, in cugraph.sssp
  File "cugraph/sssp/sssp_wrapper.pyx", line 71, in cugraph.sssp
  File "cudf/bindings/cudf_cpp.pyx", line 216, in cudf.bindings.cudf_cpp.check_gdf_error
  File "cudf/bindings/cudf_cpp.pyx", line 234, in cudf.bindings.cudf_cpp.check_gdf_error
cudf.bindings.GDFError.GDFError: CUDA ERROR. b'cudaSuccess': b'no error'
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR: RMM runtime call  RMM_FREE( (col->data), (nullptr) )an illegal memory access was encountered
^C^C^C^C^C^C^C^CAborted (core dumped)
(cugraph_dev) afender@strata3:~/sw$ python cugraph_time.py /datasets/networks/netscience.mtx --algo jaccard
ERROR:Call to cuMemcpyHtoD results in UNKNOWN_CUDA_ERROR
0.63850998878479,0.003723621368408203Traceback (most recent call last):
  File "cugraph_time.py", line 114, in <module>
    jaccard_time = jaccard_call(G)
  File "cugraph_time.py", line 52, in jaccard_call
    df = cugraph.nvJaccard(G)
  File "cugraph/jaccard/jaccard_wrapper.pyx", line 58, in cugraph.nvJaccard
  File "cugraph/jaccard/jaccard_wrapper.pyx", line 128, in cugraph.nvJaccard
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/cudf/dataframe/series.py", line 78, in __init__
    data = columnops.as_column(data, nan_as_null=nan_as_null)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/cudf/dataframe/columnops.py", line 230, in as_column
    data = as_column(rmm.to_device(arbitrary), nan_as_null=nan_as_null)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/librmm_cffi/wrapper.py", line 241, in to_device
    to.copy_to_device(ary, stream=stream)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 212, in _require_cuda_context
    return fn(*args, **kws)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/numba/cuda/cudadrv/devicearray.py", line 198, in copy_to_device
    _driver.host_to_device(self, ary_core, self.alloc_size, stream=stream)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1831, in host_to_device
    fn(device_pointer(dst), host_pointer(src), size, *varargs)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 290, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 325, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemcpyHtoD results in UNKNOWN_CUDA_ERROR
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR: RMM runtime call  RMM_FREE( (col->data), (nullptr) )an illegal memory access was encountered
Aborted (core dumped)
```

**Desktop (please complete the following information):**
CUDA 9.2 Rapids 0.6

**Comment by Iroy30** [comment]
@afender Could you confirm if PR #181 solves the issue for you

**Comment by afender** [comment]
Do you mind adding a simple test where values are provided so that we can directly know if this gets broken in the future?

**Comment by afender** [comment]
Just the same as a current test but where an array of ones is provided.

**Comment by Iroy30** [comment]
Yes
