### ISSUE TITLE
[QST] Are python e2e benchmarks still being supported?

### ISSUE THREAD

**Issue by barnes88** [rapidsai/cugraph#2379]
Hi,

I installed cugraph 22.04.00 using miniconda as described in the readme. When I try to run ./benchmarks/python_e2e/main.py to run some benchmarks it accesses a module that does not currently exist in the library. Was support dropped for these benchmarks?

```
$ python main.py --help
Traceback (most recent call last):
  File "/home/aaron/Downloads/cugraph/benchmarks/python_e2e/main.py", line 23, in <module>
    import cugraph_dask_funcs
  File "/home/aaron/Downloads/cugraph/benchmarks/python_e2e/cugraph_dask_funcs.py", line 24, in <module>
    from cugraph.dask.comms import comms as Comms
```

Modules available in cugraph.dask doesn't include comms:
```
>>> import cugraph.dask.
cugraph.dask.bfs(                          cugraph.dask.community                     cugraph.dask.hits(                         cugraph.dask.louvain(                      cugraph.dask.structure                     
cugraph.dask.centrality                    cugraph.dask.components                    cugraph.dask.katz_centrality(              cugraph.dask.pagerank(                     cugraph.dask.traversal                     
cugraph.dask.common                        cugraph.dask.get_chunksize(                cugraph.dask.link_analysis                 cugraph.dask.sssp(                         cugraph.dask.weakly_connected_components(
```

**Comment by jnke2016** [comment]
Hi @barnes88 . Thank you for your question. To further assist you, can I know the version of `cuGraph` you cloned to run the benchmarks? is it `cuGraph 22.04` ?
