### ISSUE TITLE
[BUG]: Set up a ubuntu 20.04 WSL instance, while running simple mem allocation I am getting bad_alloc error

### ISSUE THREAD

**Issue by Manoj-red-hat** [rapidsai/cugraph#2900]
### Version

rapids-22.10

### Which installation method(s) does this occur on?

Conda

### Describe the bug.

**GPU**
```
GPU processor:	NVIDIA GeForce GTX 1050
Driver version:		526.47
```
OS info WSL2/win11
```
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
**CODE**
```
import cudf
import cugraph

# read data into a cuDF DataFrame using read_csv
gdf = cudf.read_csv("a.csv", names=["src", "dst"], dtype=["int32", "int32"])

# We now have data as edge pairs
# create a Graph using the source (src) and destination (dst) vertex pairs
G = cugraph.Graph()
G.from_cudf_edgelist(gdf, source='src', destination='dst')

# Let's now get the PageRank score of each vertex by calling cugraph.pagerank
df_page = cugraph.pagerank(G)

# Let's look at the top 10 PageRank Score
df_page.sort_values('pagerank', ascending=False).head(10)
```
**a.csv**
```
1,2
1,3
1,4
1,5
1,6
1,7
1,8
1,9
```

**Error**
```
Traceback (most recent call last):
  File "/home/zetta/test.py", line 5, in <module>
    gdf = cudf.read_csv("a.csv", names=["src", "dst"], dtype=["int32", "int32"])
  File "/home/zetta/miniconda3/envs/rapids-22.10/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/zetta/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/cudf/io/csv.py", line 87, in read_csv
    df = libcudf.csv.read_csv(
  File "csv.pyx", line 430, in cudf._lib.csv.read_csv
MemoryError: std::bad_alloc: CUDA error at: /home/zetta/miniconda3/envs/rapids-22.10/include/rmm/mr/device/cuda_memory_resource.hpp
```

### Minimum reproducible example

```shell
Step 1
create wsl-2 ubuntu 20.04 instance

Step 2
create conda env 
conda create -n rapids-22.10 -c rapidsai -c conda-forge -c nvidia  \
    rapids=22.10 python=3.9 cudatoolkit=11.5 
Step 3
Run below query, it will fail with bad_alloc
import cudf
import cugraph

# read data into a cuDF DataFrame using read_csv
gdf = cudf.read_csv("a.csv", names=["src", "dst"], dtype=["int32", "int32"])

# We now have data as edge pairs
# create a Graph using the source (src) and destination (dst) vertex pairs
G = cugraph.Graph()
G.from_cudf_edgelist(gdf, source='src', destination='dst')

# Let's now get the PageRank score of each vertex by calling cugraph.pagerank
df_page = cugraph.pagerank(G)

# Let's look at the top 10 PageRank Score
df_page.sort_values('pagerank', ascending=False).head(10)
```

### Relevant log output

```
Traceback (most recent call last):
  File "/home/zetta/test.py", line 5, in <module>
    gdf = cudf.read_csv("a.csv", names=["src", "dst"], dtype=["int32", "int32"])
  File "/home/zetta/miniconda3/envs/rapids-22.10/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/zetta/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/cudf/io/csv.py", line 87, in read_csv
    df = libcudf.csv.read_csv(
  File "csv.pyx", line 430, in cudf._lib.csv.read_csv
MemoryError: std::bad_alloc: CUDA error at: /home/zetta/miniconda3/envs/rapids-22.10/include/rmm/mr/device/cuda_memory_resource.hpp
```

### Environment details

```shell
(base) zetta@LAPTOP-BNBRDNQH:~$ bash print-env.sh
<details><summary>Click here to see environment details</summary><pre>

     **git***
     Not inside a git repository

     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=20.04
     DISTRIB_CODENAME=focal
     DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
     NAME="Ubuntu"
     VERSION="20.04.5 LTS (Focal Fossa)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 20.04.5 LTS"
     VERSION_ID="20.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=focal
     UBUNTU_CODENAME=focal
     Linux LAPTOP-BNBRDNQH 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
     Wed Nov  9 20:34:42 2022
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 525.46       Driver Version: 526.47       CUDA Version: 12.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
     | N/A   48C    P8    N/A /  N/A |    982MiB /  4096MiB |      2%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+

     ***CPU***
     Architecture:                    x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Byte Order:                      Little Endian
     Address sizes:                   39 bits physical, 48 bits virtual
     CPU(s):                          6
     On-line CPU(s) list:             0-5
     Thread(s) per core:              2
     Core(s) per socket:              3
     Socket(s):                       1
     Vendor ID:                       GenuineIntel
     CPU family:                      6
     Model:                           158
     Model name:                      Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
     Stepping:                        10
     CPU MHz:                         2304.006
     BogoMIPS:                        4608.01
     Hypervisor vendor:               Microsoft
     Virtualization type:             full
     L1d cache:                       96 KiB
     L1i cache:                       96 KiB
     L2 cache:                        768 KiB
     L3 cache:                        8 MiB
     Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
     Vulnerability L1tf:              Mitigation; PTE Inversion
     Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
     Vulnerability Meltdown:          Mitigation; PTI
     Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
     Vulnerability Srbds:             Unknown: Dependent on hypervisor status
     Vulnerability Tsx async abort:   Not affected
     Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves flush_l1d arch_capabilities

     ***CMake***

     ***g++***

     ***nvcc***

     ***Python***
     /home/zetta/miniconda3/bin/python
     Python 3.9.12

     ***Environment Variables***
     PATH                            : /home/zetta/miniconda3/bin:/home/zetta/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program
     Files                           : (x86)/Common
     Files/Oracle/Java/javapath:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Program: Files/Amazon/AWSCLIV2:/mnt/c/Program
     Files/Amazon/SessionManagerPlugin/bin:/mnt/c/Program: Files/dotnet:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Program
     Files                           : (x86)/Calibre2:/mnt/c/Users/Manoj/vcpkg:/mnt/c/Program
     Files                           : (x86)/NVIDIA
     Corporation/PhysX/Common:/mnt/c/Program: Files/PuTTY:/mnt/c/Program
     Files/NVIDIA                    : GPU
     Computing                       : Toolkit/CUDA/v11.4/bin/extras/CUPTI/lib64:/mnt/c/Program
     Files                           : (x86)/Common
     Files/Oracle/Java/javapath:/mnt/c/Program: Files/NVIDIA
     GPU                             : Computing
     Toolkit/CUDA/v11.4/bin:/mnt/c/Program: Files/NVIDIA
     GPU                             : Computing
     Toolkit/CUDA/v11.4/libnvvp:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program: Files
     (x86)/NVIDIA                    : Corporation/PhysX/Common:/mnt/c/Program
     Files/NVIDIA                    : Corporation/NVIDIA
     NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Program: Files/Amazon/AWSCLIV2:/mnt/c/Program
     Files/Amazon/SessionManagerPlugin/bin:/mnt/c/Program: Files/Git/cmd:/mnt/c/Program
     Files/dotnet:/mnt/c/Program     : Files/NVIDIA
     Corporation/Nsight              : Compute
     2021.2.2:/mnt/c/Program         : Files/CMake/bin:/mnt/c/Program
     Files/Common                    : Files/Oracle/Java/javapath:/mnt/c/Program
     Files/NVIDIA                    : GPU
     Computin:/mnt/c/Users/Manoj/AppData/Local/Programs/Microsoft: VS
     Code/bin:/mnt/c/Program         : Files/JetBrains/IntelliJ
     IDEA                            : Community
     Edition                         : 2022.1.2/bin:/mnt/c/Users/Manoj/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Manoj/vcpkg:/mnt/c/Program
     Files/JetBrains/JetBrains       : Gateway
     222.2270.16/bin:/snap/bin       :
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/zetta/miniconda3
     PYTHON_PATH                     :

     ***conda packages***
     /home/zetta/miniconda3/bin/conda
     # packages in environment at /home/zetta/miniconda3:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     _openmp_mutex             4.5                       1_gnu
     brotlipy                  0.7.0           py39h27cfd23_1003
     ca-certificates           2022.3.29            h06a4308_1
     certifi                   2021.10.8        py39h06a4308_2
     cffi                      1.15.0           py39hd667e15_1
     charset-normalizer        2.0.4              pyhd3eb1b0_0
     colorama                  0.4.4              pyhd3eb1b0_0
     conda                     4.12.0           py39h06a4308_0
     conda-content-trust       0.1.1              pyhd3eb1b0_0
     conda-package-handling    1.8.1            py39h7f8727e_0
     cryptography              36.0.0           py39h9ce1e76_0
     idna                      3.3                pyhd3eb1b0_0
     ld_impl_linux-64          2.35.1               h7274673_9
     libffi                    3.3                  he6710b0_2
     libgcc-ng                 9.3.0               h5101ec6_17
     libgomp                   9.3.0               h5101ec6_17
     libstdcxx-ng              9.3.0               hd4cf53a_17
     ncurses                   6.3                  h7f8727e_2
     openssl                   1.1.1n               h7f8727e_0
     pip                       21.2.4           py39h06a4308_0
     pycosat                   0.6.3            py39h27cfd23_0
     pycparser                 2.21               pyhd3eb1b0_0
     pyopenssl                 22.0.0             pyhd3eb1b0_0
     pysocks                   1.7.1            py39h06a4308_0
     python                    3.9.12               h12debd9_0
     readline                  8.1.2                h7f8727e_1
     requests                  2.27.1             pyhd3eb1b0_0
     ruamel_yaml               0.15.100         py39h27cfd23_0
     setuptools                61.2.0           py39h06a4308_0
     six                       1.16.0             pyhd3eb1b0_1
     sqlite                    3.38.2               hc218d9a_0
     tk                        8.6.11               h1ccaba5_0
     tqdm                      4.63.0             pyhd3eb1b0_0
     tzdata                    2022a                hda174b7_0
     urllib3                   1.26.8             pyhd3eb1b0_0
     wheel                     0.37.1             pyhd3eb1b0_0
     xz                        5.2.5                h7b6447c_0
     yaml                      0.2.5                h7b6447c_0
     zlib                      1.2.12               h7f8727e_1

</pre></details>
(base) zetta@LAPTOP-BNBRDNQH:~$
```

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by Manoj-red-hat** [comment]
Latest rapids won't work on GTX 1050 as per https://github.com/rapidsai/cudf/issues/9753
