### ISSUE TITLE
`uniform_neighbor_sample` returns invalid indices when an unweighted Graph is passed

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2981]
`uniform_neighbor_sample` returns an invalid `indices` column in the returned DataFrame when an unweighted Graph is passed. Since the algo currently does not consider edge weights for sampling, the user should not need to ensure edge weights are provided.

**Comment by rlratzel** [comment]
Minimal reproducer is provided below.
Running it results in this traceback:
```
(rapids) root@8bee2113975b:/Projects/cugraph/python/cugraph-service# python tests/uns_unweighted_graph.py
Traceback (most recent call last):
  File "/Projects/cugraph/python/cugraph-service/tests/uns_unweighted_graph.py", line 29, in <module>
    indices = result_df["indices"].to_cupy()
  File "/opt/conda/envs/rapids/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/cudf/core/single_column_frame.py", line 132, in to_cupy
    return super().to_cupy(dtype, copy, na_value).flatten()
  File "/opt/conda/envs/rapids/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/cudf/core/frame.py", line 529, in to_cupy
    return self._to_array(
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/cudf/core/frame.py", line 494, in _to_array
    matrix[:, i] = get_column_values_na(col)
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/cudf/core/frame.py", line 473, in get_column_values_na
    return get_column_values(col)
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/cudf/core/frame.py", line 530, in <lambda>
    (lambda col: col.values.copy())
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/cudf/core/column/column.py", line 175, in values
    raise ValueError("Column must have no nulls.")
ValueError: Column must have no nulls.
```
Inspecting `result_df` shows the invalid `indices` column:
```
> /Projects/cugraph/python/cugraph-service/tests/uns_unweighted_graph.py(27)<module>()
-> sources = result_df["sources"].to_cupy()
(Pdb) p result_df
        indices  sources  destinations
0  1.000000e+00       33            31
1  1.000000e+00        0            13
2  0.000000e+00        8            33
3  5.605194e-45        8            30
4  1.000000e+00       30            32
5  0.000000e+00        4             0
6  2.802597e-45        4            10
7  1.000000e+00       10             5
(Pdb) c
> /Projects/cugraph/python/cugraph-service/tests/uns_unweighted_graph.py(26)<module>()
-> breakpoint()
(Pdb) p result_df
        indices  sources  destinations
0  5.605194e-45       33            31
1  1.401298e-44        0            13
2  2.242078e-44        8            33
3  9.809089e-45        8            30
4  4.203895e-44       30            32
5  0.000000e+00        4             0
6  1.401298e-45        4            10
7  5.605194e-45       10             5
(Pdb) c
> /Projects/cugraph/python/cugraph-service/tests/uns_unweighted_graph.py(27)<module>()
-> sources = result_df["sources"].to_cupy()
(Pdb) p result_df
           indices  sources  destinations
0  1.401298464e-45       33            31
1  1.401298464e-44        0            13
2  2.242077543e-44        8            33
3   9.80908925e-45        8            30
4  2.802596929e-45       30            32
5             -0.0        4             0
6             <NA>        4            10
7  2.382207389e-44       10             5
```
If a weighted graph is extraced and used, the indices column is correct:
```
(Pdb) p result_df
   indices  sources  destinations
0      1.0       33            31
1      1.0        0            13
2      1.0        8            33
3      1.0        8            30
4      1.0       30            32
5      1.0        4             0
6      1.0        4            10
7      1.0       10             5
```
[uns_unweighted_graph_py.txt](https://github.com/rapidsai/cugraph/files/10097285/uns_unweighted_graph_py.txt)

**Comment by ChuckHastings** [comment]
Can we retest this?  We have completely refactored the `uniform_neighbor_sample` code and how it handles indices.  It seems likely we have corrected this behavior.

**Comment by alexbarghi-nv** [comment]
This has been resolved.
