### ISSUE TITLE
MG `cugraph.Graph` `number_of_vertices()`, `edges()` have incorrect hard-coded column names, raises exception

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cugraph#2989]
The `number_of_vertices()` and `edges()` methods for `cugraph.Graph` objects is broken for multi-GPU graphs.  A minimal reproducer is below, along with the output of running it:
```python
import dask_cudf
import cugraph
from cugraph.experimental import datasets

# testing.mg_utils is not part of cugraph yet, but will be in a future PR
from cugraph.testing.mg_utils import start_dask_client, stop_dask_client


if __name__ == "__main__":
    dask_client = start_dask_client()

    ddf = dask_cudf.from_cudf(datasets.karate.get_edgelist(), npartitions=2)
    G = cugraph.Graph()
    G.from_dask_cudf_edgelist(ddf, source="src", destination="dst", edge_attr="wgt")

    num_verts = G.number_of_vertices()
    print(f"karate has {num_verts} vertices")

    edges = G.edges()
```
```
Traceback (most recent call last):
  File "/Projects/cugraph/mr.py", line 13, in <module>
    G.number_of_vertices()
  File "/Projects/cugraph/python/cugraph/cugraph/structure/graph_implementation/simpleDistributedGraph.py", line 337, in number_of_vertices
    ddf = self.edgelist.edgelist_df[["src", "dst"]]
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/dask/dataframe/core.py", line 4615, in __getitem__
    meta = self._meta[_extract_meta(key)]
  File "/opt/conda/envs/rapids/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/cudf/core/dataframe.py", line 1169, in __getitem__
    return self._get_columns_by_label(mask)
  File "/opt/conda/envs/rapids/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/cudf/core/dataframe.py", line 1893, in _get_columns_by_label
    new_data = super()._get_columns_by_label(labels, downcast)
  File "/opt/conda/envs/rapids/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/cudf/core/frame.py", line 414, in _get_columns_by_label
    return self._data.select_by_label(labels)
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/cudf/core/column_accessor.py", line 338, in select_by_label
    return self._select_by_label_list_like(key)
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/cudf/core/column_accessor.py", line 453, in _select_by_label_list_like
    data = {k: self._grouped_data[k] for k in key}
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/cudf/core/column_accessor.py", line 453, in <dictcomp>
    data = {k: self._grouped_data[k] for k in key}
KeyError: 'src'
```

**Comment by rlratzel** [comment]
update: `edges()` has the same problem so I've updated the description above.

**Comment by rlratzel** [comment]
closed by PR https://github.com/rapidsai/cugraph/pull/3757
