### ISSUE TITLE
cugraph algos like sssp gives error when create graph with from_cudf_adjlist used, which is newly fixed bug in 22.12

### ISSUE THREAD

**Issue by Ankitkurani1997** [rapidsai/cugraph#3163]
### Version

22.12

### Which installation method(s) does this occur on?

Conda

### Describe the bug.

@ChuckHastings @BradReesWork 

Tried to run the sssp algorithm when the graph object is created from  from_cudf_adjlist flow

Wanted to provide the input graph format in csr format only and not edgelist format.

Got error while running the code

In github issue #3016  and #3027  , only louvain algorithm flow was tested, please also check for other graph algorithms as well.

I am using twitter data set here 

pdf = pd.read_csv("../data/140m_twitter-2010.csv", delimiter=' ', names=['src', 'dst'], dtype={'src':'int32', 'dst': 'int32'})
pdf["data"] = 1.0

### Minimum reproducible example

```shell
import cupy
import scipy
import cudf
import cugraph
M = scipy.sparse.coo_matrix((M["data"], (M['src'],M['dst'])))
M = M.tocsr()
offsets = cudf.Series(M.indptr)
indices = cudf.Series(M.indices)
weigths = cudf.Series(M.data)
G_csr = cugraph.Graph()
G_csr.from_cudf_adjlist(offsets, indices, weigths)
result = cugraph.sssp(G_csr, 1)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/ankit/rapids/graph/graph-analytics/plain_uvm_sssp.py", line 62, in <module>
    shortest_path_df = cugraph.sssp(G, 1)
  File "/home/ankit/miniconda3/envs/rapids-22.12/lib/python3.9/site-packages/cugraph/traversal/sssp.py", line 219, in sssp
    if not G.edgelist.weights:
AttributeError: 'NoneType' object has no attribute 'weights'
```

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by Ankitkurani1997** [comment]
@ChuckHastings @rlratzel @raydouglass 
Please help to check this issue
