### ISSUE TITLE
[BUG]: cugraph-dgl example crashed

### ISSUE THREAD

**Issue by chang-l** [rapidsai/cugraph#3847]
### Version

22.10

### Which installation method(s) does this occur on?

Source

### Describe the bug.

According to [README](https://github.com/rapidsai/cugraph/blob/branch-23.10/python/cugraph-dgl/examples/graphsage/README.MD),  the following cmd failed:
`python3 node_classification.py --mode=gpu_cugraph_dgl`

### Relevant log output

```shell
Traceback (most recent call last):
  File "/opt/dgl/qa/L1_cuGraph_GraphSAGE_1GPU/node.py", line 230, in <module>
    set_allocators()
  File "/opt/dgl/qa/L1_cuGraph_GraphSAGE_1GPU/node.py", line 48, in set_allocators
    torch.cuda.memory.change_current_allocator(rmm.rmm_torch_allocator)
AttributeError: module 'rmm' has no attribute 'rmm_torch_allocator'
```

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by chang-l** [comment]
Looks like we should import `rmm_torch_allocator` as:
```
from rmm.allocators.torch import rmm_torch_allocator
```
