### ISSUE TITLE
[BUG] Error when exiting in SSSP tests

### ISSUE THREAD

**Issue by afender** [rapidsai/cugraph#424]
This seems to be a regression that happend during 0.9.
The error is not caught by pytest or gpuCI 

```
(cugraph_dev) afender@strata3:~/sw/cugraph/python$ pytest cugraph/tests/test_sssp.py::test_sssp
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/afender/sw/cugraph/python
collected 12 items                                                                                                                                                                                         

cugraph/tests/test_sssp.py ............                                                                                                                                                              [100%]

======================================================================================== 12 passed in 3.36 seconds =========================================================================================
Traceback (most recent call last):
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/numba/utils.py", line 745, in _exitfunc
    f()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/numba/utils.py", line 669, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1037, in core
    dealloc.add_item(module_unload, handle)
AttributeError: 'NoneType' object has no attribute 'add_item'
Traceback (most recent call last):
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/numba/utils.py", line 745, in _exitfunc
    f()
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/numba/utils.py", line 669, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/afender/anaconda3/envs/cugraph_dev/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1037, in core
    dealloc.add_item(module_unload, handle)
AttributeError: 'NoneType' object has no attribute 'add_item'
```

**Comment by afender** [comment]
Doesn't repro
