### ISSUE TITLE
[BUG]: cannot install cugraph 

### ISSUE THREAD

**Issue by gaokaige1996** [rapidsai/cugraph#4343]
### Version

cugraph 24.4

### Which installation method(s) does this occur on?

Pip

### Describe the bug.

I tried to install "!pip install \
    --extra-index-url=https://pypi.nvidia.com \
    cudf-cu12==24.4.* cugraph-cu12==24.4.*"
error: subprocess-exited-with-error

but it says that the   " raise RuntimeError(f"Didn't find wheel for {distribution} {version}"
 Could you please help me take a look at that and let me know if there is something wrong here?
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [56 lines of output]
    File "C:\Users\fanyu\AppData\Local\Temp\pip-build-env-_j7hqydb\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 148, in download_wheel
      return download_manual(wheel_directory, distribution, version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\fanyu\AppData\Local\Temp\pip-build-env-_j7hqydb\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 115, in download_manual
      raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
  Traceback (most recent call last):
    File "C:\Users\fanyu\AppData\Local\Temp\pip-build-env-_j7hqydb\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 148, in download_wheel
      return download_manual(wheel_directory, distribution, version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\fanyu\AppData\Local\Temp\pip-build-env-_j7hqydb\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 115, in download_manual
      raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
  RuntimeError: Didn't find wheel for cudf-cu12 24.4.0
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "C:\Users\fanyu\Anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\fanyu\Anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\fanyu\Anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\fanyu\AppData\Local\Temp\pip-build-env-_j7hqydb\overlay\Lib\site-packages\nvidia_stub\buildapi.py", line 29, in build_wheel
      return download_wheel(pathlib.Path(wheel_directory), config_settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\fanyu\AppData\Local\Temp\pip-build-env-_j7hqydb\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 150, in download_wheel
      report_install_failure(distribution, version, exception_context)
    File "C:\Users\fanyu\AppData\Local\Temp\pip-build-env-_j7hqydb\overlay\Lib\site-packages\nvidia_stub\error.py", line 63, in report_install_failure
      raise InstallFailedError(
  nvidia_stub.error.InstallFailedError:
  *******************************************************************************
  
  The installation of cudf-cu12 for version 24.4.0 failed.
  
  This is a special placeholder package which downloads a real wheel package
  from https://pypi.nvidia.com./ If https://pypi.nvidia.com/ is not reachable, we
  cannot download the real wheel file to install.
  
  You might try installing this package via
  ```
  $ pip install --extra-index-url https://pypi.nvidia.com/ cudf-cu12
  ```
  
  Here is some debug information about your platform to include in any bug
  report:
  
  Python Version: CPython 3.11.5
  Operating System: Windows 10
  CPU Architecture: AMD64
  Driver Version: 552.12
  CUDA Version: 12.4
  
  *******************************************************************************
  
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Environment details

```shell
Here is some debug information about your platform to include in any bug
  report:
  
  Python Version: CPython 3.11.5
  Operating System: Windows 10
  CPU Architecture: AMD64
  Driver Version: 552.12
  CUDA Version: 12.4
```

### Code of Conduct

- [X] I agree to follow cuGraph's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by rlratzel** [comment]
Hi @gaokaige1996 , have you been able to try the install using WSL2 as @alexbarghi-nv suggested ( https://docs.rapids.ai/install#wsl2 ) ?

**Comment by rlratzel** [comment]
@gaokaige1996 , I'm going to close this but please re-open it if you're still seeing the problem after using the above suggestions.
