### ISSUE TITLE
[BUG]: AttributeError when importing cugraph

### ISSUE THREAD

**Issue by marhofmann** [rapidsai/cugraph#4745]
### Version

cugraph-cu11-24.10.0

### Which installation method(s) does this occur on?

Pip

### Describe the bug.

I installed cugraph using the following command:

`$ pip install cugraph-cu11 --extra-index-url=https://pypi.nvidia.com`

When I import cugraph in a python console with `import cugraph` i get the AttributeError `AttributeError: module 'cuda.ccudart' has no attribute '__pyx_capi__`

Please help

### Minimum reproducible example

import cugraph

### Relevant log output

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/XXX/venv/lib/python3.10/site-packages/cugraph/__init__.py", line 14, in <module>
    from cugraph.community import (
  File "/XXX/venv/lib/python3.10/site-packages/cugraph/community/__init__.py", line 14, in <module>
    from cugraph.community.louvain import louvain
  File "/XXX/venv/lib/python3.10/site-packages/cugraph/community/louvain.py", line 15, in <module>
    from cugraph.structure import Graph
  File "/XXX/venv/lib/python3.10/site-packages/cugraph/structure/__init__.py", line 14, in <module>
    from cugraph.structure.graph_classes import (
  File "/XXXvenv/lib/python3.10/site-packages/cugraph/structure/graph_classes.py", line 15, in <module>
    from .graph_implementation import (
  File "/XXXvenv/lib/python3.10/site-packages/cugraph/structure/graph_implementation/__init__.py", line 14, in <module>
    from .simpleGraph import simpleGraphImpl
  File "/XXX/venv/lib/python3.10/site-packages/cugraph/structure/graph_implementation/simpleGraph.py", line 14, in <module>
    from cugraph.structure import graph_primtypes_wrapper
  File "graph_primtypes_wrapper.pyx", line 1, in init cugraph.structure.graph_primtypes_wrapper
  File "/XXX/venv/lib/python3.10/site-packages/pylibraft/common/__init__.py", line 18, in <module>
    from .cuda import Stream
  File "cuda.pyx", line 1, in init pylibraft.common.cuda
AttributeError: module 'cuda.ccudart' has no attribute '__pyx_capi__'

### Environment details

- Ubuntu 22.04.5
- Python 3.10
- Cuda toolkit version 11.5.1-lubuntu1
- A16 with driver Version NVIDIA-SMI 550.54.14 

### Code of Conduct

- [x] I agree to follow cuGraph's Code of Conduct
- [x] I have searched the [open bugs](https://github.com/rapidsai/cugraph/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by leofang** [comment]
This is tracked in https://github.com/NVIDIA/cuda-python/issues/215. We are working on it. For the time being please downgrade your cuda-python version as instructed there.

**Comment by rlratzel** [comment]
@marhofmann are you still seeing the same `AttributeError` now that https://github.com/NVIDIA/cuda-python/issues/215 is closed?

**Comment by ChuckHastings** [comment]
Going to close this issue.  @marhofmann - if you are still seeing this error, please let us know and reopen this issue.
