### ISSUE TITLE
[BUG] Revert temporary fix for get_ipc_handle() in snmg pagerank

### ISSUE THREAD

**Issue by Iroy30** [rapidsai/cugraph#790]
**Describe the bug**
get_ipc_handle() fails in snmg pagerank. This is from a bug within numba. The temporary solution to avoid that is already implemented via ducktyping (PR #728). Once the bug is fixed within numba, the temporary fix needs to be reverted.

**To Reproduce**
>>> import cudf
>>> df =cudf.DataFrame()
>>> df['src']=[1,2,3]
>>> df['src']._column.data_array_view.get_ipc_handle()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/iroy/.conda/envs/snmg_pr/lib/python3.7/site-packages/numba/cuda/cudadrv/devicearray.py", line 320, in get_ipc_handle
    ipch = devices.get_context().get_ipc_handle(self.gpu_data)
  File "/home/iroy/.conda/envs/snmg_pr/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 847, in get_ipc_handle
    memory.owner.handle,
AttributeError: 'Buffer' object has no attribute 'handle'

**Comment by Iroy30** [comment]
the corresponding numba Issue and fix to be tracked:
Issue: https://github.com/numba/numba/issues/5429
PR: https://github.com/numba/numba/pull/5437

**Comment by BradReesWork** [comment]
SNMG version is being dropping for OPG.  Closing issue
